// <auto-generated />
namespace VehicleTender.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migv131 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migv131));
        
        string IMigrationMetadata.Id
        {
            get { return "202304301027249_migv131"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
